spring.application.name=api
spring.jpa.show-sql=true

# Usar "update" cuando se esta en desarrollo
# -Comprueba tus entidades con las tablas, actualizandolas de ser necesario
# Usar "create" cuando se quiere un base de datos limpia (buena para tests)
# -Borra los datos cuando se reinicia el servidor
# Usar "validate" en producción
# -Compara tus entidades con la base de datos
# Usar "none" en produccion
# -No hara nada, asume que la BD esta bien creada por lo que no hace ninguna operación
spring.jpa.hibernate.ddl-auto=update 

jwt.secret=UnaClaveSecretaParaFirmarTusJWTTokensYQueNadieLosFalsifiqueEsImportante
jwt.expiration=500000